global using Microsoft.Extensions.DependencyInjection;
global using Models.Settings;
global using Spending.Api.Protos;
global using System.Data;
global using static Spending.Api.Protos.Spending;
global using static Spending.Api.Protos.User;
global using DisCatSharp;
global using DisCatSharp.ApplicationCommands;
global using DisCatSharp.CommandsNext;
global using DisCatSharp.Entities;
global using DisCatSharp.Enums;
global using DisCatSharp.Lavalink;
global using DisCatSharp.Net;
global using Discord.Bot.Extensions;
global using Discord.Bot.Lavalink;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using System.Text.Json;
global using  Grpc.Net.Client;
global using DisCatSharp.Lavalink.Entities;
global using DisCatSharp.Lavalink.Enums;
global using DisCatSharp.ApplicationCommands.Attributes;
global using DisCatSharp.ApplicationCommands.Context;
global using DisCatSharp.CommandsNext.Attributes;
