version: '3.4'

services:
  spending:
    env_file: .env.${ENV_NAME}
    image: hqtruong27/spending.api:latest
    build:
      context: .
      dockerfile: Microservices/Spending/Spending.Api/Dockerfile
    networks:
      - proxy-manager_default
   
  discord:
    image: hqtruong27/discord.bot:latest
    env_file: .env.${ENV_NAME}
    build:
      context: .
      dockerfile: Microservices/Discord/Discord.Bot/Dockerfile

  db:
    image: postgres
    restart: always
    env_file: .env.${ENV_NAME}
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - proxy-manager_default
  
  mongodb:
    image: mongo:latest
    restart: always
    env_file: .env.${ENV_NAME}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - proxy-manager_default

networks:
  proxy-manager_default:
    external: true
    driver: bridge
    ipam:
      driver: default