version: '3.4'

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
     - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
     - ~/.aspnet/https:/home/app/.aspnet/https:ro