version: '3.4'

services:
  webapi:
    image: hqtruong27/webapi-service:latest
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    networks:
      - proxy-manager_default

  discord:
    image: hqtruong27/discord-service:latest
    build:
      context: .
      dockerfile: Discord/Dockerfile
    env_file:
      - .env.${ENV_NAME}

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - proxy-manager_default

networks:
  proxy-manager_default:
    external: true