version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  discord:
    image: ${DOCKER_REGISTRY-}discord
    build:
      context: .
      dockerfile: Discord/Dockerfile

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/kaname-madoka.com/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/kaname-madoka.com/privkey.pem:/etc/nginx/certs/privkey.pem
      - ./nginx.conf:/etc/nginx/nginx.conf