services:
  
  hoyoverse:
    env_file: .env.production
    image: hqtruong27/hoyoverse-api:latest
    container_name: hoyoverse
    restart: always
    ports:
      - "8080"
      - "8081"
    build:
      context: .
      dockerfile: Microservices/Hoyoverse/Hoyoverse.Api/Dockerfile
    networks:
      - random
    depends_on:
      - mongodb
      
  spending:
    env_file: .env.production
    image: hqtruong27/spending.api:latest
    container_name: spending
    restart: always
    build:
      context: .
      dockerfile: Microservices/Spending/Spending.Api/Dockerfile
    networks:
      - random
    depends_on:
      - postgresql
   
  discord:
    image: hqtruong27/discord.bot:latest
    restart: always
    container_name: discord
    env_file: .env.production
    build:
      context: .
      dockerfile: Microservices/Discord/Discord.Bot/Dockerfile
    depends_on:
      lavalink:
        condition: service_healthy
      spending:
        condition: service_started
    networks:
      - random

  postgresql:
    image: postgresql
    restart: always
    container_name: postgresql
    env_file: .env.production
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - random
  
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    env_file: .env.production
    volumes:
      - ./mongodb:/data/db
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
    networks:
      - random

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: always
    env_file: .env.production
    volumes:
      # mount application.yml from the same directory or use environment variables
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
      - ./lavalink/plugins/:/opt/Lavalink/plugins/
    networks:
      - random
    expose:
      # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
      - 2333
    ports:
      # you only need this if you want to make your lavalink accessible from outside of containers
      - "2333:2333"
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "GET", "${HEALTH_CHECK_URL}", "-H", "Authorization: ${LAVALINK_SERVER_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  random:
    name: random
    driver: bridge
    ipam:
      driver: default
      #use IP windows for internal network, for wsl see README.md
      config:
        - subnet: 172.22.130.0/24