version: '3.4'

services:
  webapi:
    image: hqtruong27/webapi-service:latest
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    networks:
      - proxy-manager_default

  discord:
    image: hqtruong27/discord-service:latest
    build:
      context: .
      dockerfile: Discord/Dockerfile

networks:
  proxy-manager_default:
    external: true