name: CI/CD Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  docker-login:
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        run: docker login harbor.kaname-madoka.com -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}

  build:
    needs: docker-login
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker images
        run: |
          docker login harbor.kaname-madoka.com -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
          docker build -t harbor.kaname-madoka.com/demo/discord-service:${{ github.sha }} -f Discord/Dockerfile .
          docker build -t harbor.kaname-madoka.com/demo/webapi-service:${{ github.sha }} -f WebApi/Dockerfile .
          docker push harbor.kaname-madoka.com/demo/discord-service:${{ github.sha }}
          docker push harbor.kaname-madoka.com/demo/webapi-service:${{ github.sha }}

  copy-ssh-key:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH Directory
        run: mkdir -p ~/.ssh

      - name: Copy SSH key
        run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        
  deploy:
    needs: [build, copy-ssh-key, docker-login]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Docker Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login harbor.kaname-madoka.com -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
            docker pull harbor.kaname-madoka.com/demo/discord-service:${{ github.sha }}
            docker pull harbor.kaname-madoka.com/demo/webapi-service:${{ github.sha }}
            docker compose up -d
