name: CI/CD Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  docker-login:
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        run: docker login harbor.kaname-madoka.com -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}

  build:
    needs: docker-login
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker images
        run: |
          docker login harbor.kaname-madoka.com -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
          docker build -t harbor.kaname-madoka.com/demo/discord-service:${{ github.sha }} -f Discord/Dockerfile .
          docker build -t harbor.kaname-madoka.com/demo/webapi-service:${{ github.sha }} -f WebApi/Dockerfile .
          docker push harbor.kaname-madoka.com/demo/discord-service:${{ github.sha }}
          docker push harbor.kaname-madoka.com/demo/webapi-service:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Docker Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login harbor.kaname-madoka.com -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
            docker pull harbor.kaname-madoka.com/demo/discord-service:${{ github.sha }}
            docker pull harbor.kaname-madoka.com/demo/webapi-service:${{ github.sha }}
            docker-compose up -d
