name: CI/CD Build and Deploy

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: |
          docker login harbor.kaname-madoka.com -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
          
      - name: Docker build and push Discord service
        run: |
          docker build -t harbor.kaname-madoka.com/demo/discord-service:latest -f Discord/Dockerfile .
          docker push harbor.kaname-madoka.com/demo/discord-service:latest

      - name: Docker build and push WebApi service
        run: |
          docker build -t harbor.kaname-madoka.com/demo/webapi-service:latest -f WebApi/Dockerfile .
          docker push harbor.kaname-madoka.com/demo/webapi-service:latest

  copy-ssh-key:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH Directory
        run: mkdir -p ~/.ssh

      - name: Copy SSH key
        run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        
  deploy:
    needs: [build, copy-ssh-key]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Docker Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login harbor.kaname-madoka.com -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
            docker pull harbor.kaname-madoka.com/demo/discord-service:latest
            docker pull harbor.kaname-madoka.com/demo/webapi-service:latest
            docker compose -f random/docker-compose.yml up -d
